### ISSUE TITLE
github token printed in verbose mode

### ISSUE THREAD

**Issue by zephraph** [intuit/auto-release#132] opened 2019-01-04 04:15 UTC
**Describe the bug**

When printing out configuration via verbose mode it prints out the github token. If you're attempting to debug an issue on public CI this'll expose credentials to the public. 

**To Reproduce**

Run `auto shipit --very-verbose`

**Expected behavior**

The github token should be sanitized or removed. 

**Screenshots**

<img width="420" alt="image" src="https://user-images.githubusercontent.com/3087225/50673562-4b117800-0fa4-11e9-8d41-0d6b970787fd.png">

_(this token was invalidated)_

**Comment by hipstersmoothie** [comment] 2019-01-04 07:43
Is that with these changes? https://github.com/intuit/auto-release/pull/130? 

I'm thinking it's probably this line where it gets printed https://github.com/intuit/auto-release/blob/master/src/github-release.ts#L169

I can make a PR for this tomorrow it'll just be copying the code for now. I am working on a slight rewrite that will get rid of the branching in the constructor https://github.com/intuit/auto-release/pull/131/files#diff-50f0d7708b5c1cb25e0811ab4004421fR134. 

Sorry for the leaked key!

**Comment by orta** [comment] 2019-01-04 12:20
Yep, this is a dupe of #130

**Closed** 2019-01-06 05:02 UTC
Labels: bug
